services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: get-p-server
    env_file:
      - .env.dev
    depends_on:
      - redis
      - database
    ports:
      - ${SPRING_PORT}:${SPRING_PORT}
    restart: always
    volumes:
      - /data:/storage

  database:
    image: mysql:9.0.0
    container_name: get-p-database
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command:
      --port=${DB_PORT} --max_allowed_packet=32M
    expose:
      - ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: always
    volumes:
      - get-p-database:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: get-p-redis
    command: --port ${REDIS_PORT} --requirepass ${REDIS_PASSWORD}
    expose:
      - ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - get-p-redis:/data
    restart: always

volumes:
  get-p-database:
  get-p-redis: